### PR TITLE
modified python-parser code for building multi level fold tree.

### PR DESCRIPTION
**Pull request by Csomnia**
#55

### CODE REVIEW

**Comment by sawan** [comment]
Thank you, this works for second level nodes -- tested via patching latest from ELPA.

But not for anything indented beyond that for, examples nested loops, try-catch, etc. Is it possible to have these? As they are clearly indentation dependent.

**Comment by wbolster** [comment]
@sawan  you could try removing the python specific parser from `origami-parser-alist`. i think the fallback is purely indentation based.

**Comment by sawan** [comment]
Ah... how do I do that please?

**Comment by wbolster** [comment]
many ways to do it. easiest is via the customize interface:

```
M-x customize-variable RET origami-parser-alist RET
```

**Comment by wbolster** [comment]
alternatively, with `imenu` parsing from #69 python looks like this:

image

**Comment by VelikiiNehochuha** [comment]
Done python parser for any block of codes (if try for, etc.. ) https://github.com/gregsexton/origami.el/pull/91

**Comment by gregsexton** [comment]
This is great.

**Comment by conao3** [comment]
This change pollutes the user's `python-` namespace because it defines a `python-subparser` globally.
I recommend revert it.

**Comment by wbolster** [comment]
hey @conao3 maybe don't pop out of nowhere to shout negative things. it's rude behaviour.

instead, you could have written something this:

'it seems this change introduced a function that looks like it's on the global python namespace (`python-subparser`), and it doesn't belong there. i suggest renaming it to `origami-python-subparser`. let me know if i should open a pull request for this.'

see the difference? no bitching, no mention of blindly reverting (counterproductive suggestion) but an actionable improvement with an offer to help.

in fact, opening a pull request to improve the situation would probably have taken you less time than writing your negative comment.

you're welcome.

**Comment by conao3** [comment]
In fact, I think it's better to use `lambda` or `cl-flet` than to use `origami-python-` prefixes.
It seems a bit odd to dynamically declare a global function in some function...

**Comment by gregsexton** [comment]
I'll merge a PR

**Comment by alphapapa** [comment]
> hey @conao3 maybe don't pop out of nowhere to shout negative things. it's rude behaviour.
> 
> instead, you could have written something this:
> 
> 'it seems this change introduced a function that looks like it's on the global python namespace (`python-subparser`), and it doesn't belong there. i suggest renaming it to `origami-python-subparser`. let me know if i should open a pull request for this.'
> 
> see the difference? no bitching, no mention of blindly reverting (counterproductive suggestion) but an actionable improvement with an offer to help.
> 
> in fact, opening a pull request to improve the situation would probably have taken you less time than writing your negative comment.
> 
> you're welcome.

@wbolster Naoya and I have our differences sometimes, but I'll stand up for him here.  He simply observed a problem.  He was not rude.

In contrast, your comment was very rude and completely uncalled for.  What you accuse him of doing is actually what you have done.

There are real people on the other end of these screens.  What we're talking about is just code.  There's no need to be hostile.

**Comment by conao3** [comment]
While we may get confused about saying thank you, I simply want to say. Thank you, @alphapapa.

Anyway, it's been over a week without any corrections since I reported.
@gregsexton needs to fulfill its responsibilities as the owner of this project.

This package has many users and 56,000 over DLs from [MELPA](https://melpa.org/#/?q=origami).
If @gregsexton are tired and do not want to manage this package in the future, you may want to transfer it to [emacsorphanage](https://github.com/emacsorphanage) and let someone else manage it.

FYI: @jcs090218

**Comment by wbolster** [comment]
> Anyway, it's been over a week without any corrections since I reported.

@gregsexton made it clear [that he would merge a pr](https://github.com/gregsexton/origami.el/pull/64#issuecomment-612064598) and since you have a clear [idea on what the best fix would look like](https://github.com/gregsexton/origami.el/pull/64#issuecomment-610074496), a pull request is the way to get this issue to move forward.

in any case, let's keep the right perspective: this seems a _cosmetic_ issue only, and there is really no need to talk about

> @gregsexton needs to fulfill its responsibilities as the owner of this project

when a cosmetic issue isn't addressed within a few days.

**Pull request merged**
